In [1]:
import sys
print(sys.executable)

c:\Users\Karnaveer Singh\Justice_Hq\.venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np

print("--- Step 1: Filtering for Commercial Law Acts ---")
# Load the act key sitting directly in your current directory
act_key = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\acts_sections.csv")

--- Step 1: Filtering for Commercial Law Acts ---

C:\Users\Karnaveer Singh\AppData\Local\Temp\ipykernel_3276\3987080195.py:6: DtypeWarning: Columns (0: bailable_ipc) have mixed types. Specify dtype option on import or set low_memory=False.
  act_key = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\acts_sections.csv")

In [3]:
act_key.head()

,ddl_case_id,act,section,bailable_ipc,number_sections_ipc,criminal
0,06-03-02-210100004042014,17353.0,NaN,NaN,1.0,1
1,23-34-01-229900001012019,4759.0,NaN,NaN,NaN,1
2,13-18-03-204000030972016,17353.0,NaN,NaN,1.0,1
3,23-28-01-220102000232016,4759.0,NaN,NaN,NaN,1
4,01-35-05-203007002652012,17353.0,NaN,NaN,1.0,1

In [4]:
cases_2018 = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\cases\\cases_2018.csv")

In [5]:
cases_2018.head()

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list
0,01-01-01-201900000012018,2018,1,1,1,MHNB030000022018,chief judicial magistrate,0 male,0 male,-9999,0,1943,2975.0,33,2018-01-01,2018-02-07,2018-01-01,2018-02-07,2018-02-07
1,01-01-01-201900000022018,2018,1,1,1,MHNB030000032018,chief judicial magistrate,0 male,0 male,-9999,0,1943,3315.0,52,2018-01-01,2018-02-01,2018-01-01,2018-02-01,2018-02-01
2,01-01-01-201900000032018,2018,1,1,1,MHNB030000042018,chief judicial magistrate,0 male,0 male,-9999,0,1943,5877.0,52,2018-01-01,2018-02-01,2018-01-01,2018-02-01,2018-02-01
3,01-01-01-201900000042018,2018,1,1,1,MHNB030000052018,chief judicial magistrate,0 male,0 male,-9999,0,1943,840.0,52,2018-01-01,2018-02-01,2018-01-01,2018-02-01,2018-02-01
4,01-01-01-201900000052018,2018,1,1,1,MHNB030000062018,chief judicial magistrate,-9998 unclear,0 male,-9999,1,1943,840.0,5,2018-01-01,2018-01-09,2018-01-01,2018-01-09,2018-01-09

In [6]:
print(cases_2018.columns)
print(act_key.columns)

Index(['ddl_case_id', 'year', 'state_code', 'dist_code', 'court_no', 'cino',
       'judge_position', 'female_defendant', 'female_petitioner',
       'female_adv_def', 'female_adv_pet', 'type_name', 'purpose_name',
       'disp_name', 'date_of_filing', 'date_of_decision', 'date_first_list',
       'date_last_list', 'date_next_list'],
      dtype='str')
Index(['ddl_case_id', 'act', 'section', 'bailable_ipc', 'number_sections_ipc',
       'criminal'],
      dtype='str')

In [7]:
judges = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\judges_clean.csv")

In [8]:
print(cases_2018.columns)
print(act_key.columns)
print(judges.columns)

Index(['ddl_case_id', 'year', 'state_code', 'dist_code', 'court_no', 'cino',
       'judge_position', 'female_defendant', 'female_petitioner',
       'female_adv_def', 'female_adv_pet', 'type_name', 'purpose_name',
       'disp_name', 'date_of_filing', 'date_of_decision', 'date_first_list',
       'date_last_list', 'date_next_list'],
      dtype='str')
Index(['ddl_case_id', 'act', 'section', 'bailable_ipc', 'number_sections_ipc',
       'criminal'],
      dtype='str')
Index(['ddl_judge_id', 'state_code', 'dist_code', 'court_no', 'judge_position',
       'female_judge', 'start_date', 'end_date'],
      dtype='str')

In [9]:
judges.head()

,ddl_judge_id,state_code,dist_code,court_no,judge_position,female_judge,start_date,end_date
0,1,1,1,1,chief judicial magistrate,0 nonfemale,20-09-2013,20-02-2014
1,2,1,1,1,chief judicial magistrate,0 nonfemale,31-10-2013,20-02-2014
2,3,1,1,1,chief judicial magistrate,0 nonfemale,21-02-2014,31-05-2016
3,4,1,1,1,chief judicial magistrate,0 nonfemale,01-06-2016,06-06-2016
4,5,1,1,1,chief judicial magistrate,0 nonfemale,06-06-2016,07-07-2018

## 1. Core Dataset Schemas

The primary tables are compressed as numerical representations to ensure optimal processing speeds and storage footprint. 

### A. The Cases Table (`cases_yyyy.csv`)
This is the foundational lifecycle log for every lawsuit filed in the lower judiciary.

| Feature Name | Data Type | Description & Pipeline Utility |
| :--- | :--- | :--- |
| `ddl_case_id` | `string` | **Primary Key**. A unique, randomized identifier for every single court case. Used to link all lookup reference tables. |
| `year` | `integer` | The calendar year the lawsuit was officially filed in court. |
| `state_code` | `integer` | Numeric code indicating the state jurisdiction. Maps to `cases_state_key.csv`. |
| `dist_code` | `integer` | Numeric code indicating the district jurisdiction. Maps to `cases_district_key.csv`. |
| `court_no` | `integer` | Numeric code identifying the exact courtroom inside the designated district. Maps to `cases_court_key.csv`. |
| `cino` | `string` | **Case Information Number**. The official tracking identifier used inside the live government e-Courts web platform. |
| `judge_position` | `integer` | Numeric identifier representing the official rank or designation of the presiding judge. |
| `female_defendant` | `binary (0/1)`| LSTM name-classifier prediction indicating if the respondent/accused party is female. |
| `female_petitioner` | `binary (0/1)`| LSTM name-classifier prediction indicating if the plaintiff/petitioner is female. |
| `female_adv_def` | `binary (0/1)`| LSTM name-classifier prediction indicating if the defense lawyer is female. |
| `female_adv_pet` | `binary (0/1)`| LSTM name-classifier prediction indicating if the petitioner's lawyer is female. |
| `type_name` | `integer` | Numeric identifier representing the specific case classification. Maps to `type_name_key.csv`. |
| `purpose_name` | `integer` | Numeric identifier tracking the objective of a given scheduled listing. Maps to `purpose_name_key.csv`. |
| `disp_name` | `integer` | Numeric identifier indicating how the case wrapped up. Maps to `disp_name_key.csv`. |
| `date_of_filing` | `date` | The exact day the lawsuit was submitted to the court registry. Used to compute **Case Duration**. |
| `date_of_decision` | `date` | The exact day the case reached its final disposition. Used to compute **Case Duration**. |
| `date_first_list` | `date` | The procedural date indicating when the case first appeared on a judge's physical cause list. |
| `date_last_list` | `date` | The calendar date of the most recent historical hearing. |
| `date_next_list` | `date` | The upcoming scheduled hearing assignment date (null if the case is already resolved). |

### B. The Judges Profiles Table (`judges_clean.csv`)
This table acts as a log capturing judicial movements, seat transfers, and courtroom tenures.

| Feature Name | Data Type | Description & Pipeline Utility |
| :--- | :--- | :--- |
| `ddl_judge_id` | `string` | Unique identifier tracking individual judges across varying courtroom assignments. |
| `state_code` | `integer` | Numeric code mapping the state where the judge is actively deployed. |
| `dist_code` | `integer` | Numeric code mapping the specific judicial district of deployment. |
| `court_no` | `integer` | The designated courtroom number where the judge is presiding. |
| `judge_position` | `integer` | The designation ranking of the judge. Matches the `judge_position` field in the cases table. |
| `female_judge` | `binary (0/1)`| Name-classifier prediction indicating if the judge identifies as female. |
| `start_date` | `date` | The timestamp marking exactly when this judge assumed control of this specific courtroom seat. |
| `end_date` | `date` | The timestamp marking when the judge rotated out of this specific courtroom assignment. |

### C. The Acts & Sections Table (`acts_sections.csv`)
*Note: In specific versions of this public repository, this mapping dataset focuses heavily on criminal metadata rather than purely commercial act names.*

| Feature Name | Data Type | Description & Pipeline Utility |
| :--- | :--- | :--- |
| `ddl_case_id` | `string` | Foreign key mapping back to the primary case file records. |
| `act` | `integer` | Numeric identifier for the parent legislation. Maps to `act_key.csv`. |
| `section` | `integer` | Numeric identifier for the precise section/clause. Maps to `section_key.csv`. |
| `bailable_ipc` | `binary (0/1)`| Categorical flag tracking whether an IPC violation charge is a bailable offense. |
| `number_sections_ipc`| `integer` | Continuous count tracking total Indian Penal Code sections invoked under the case ID. |
| `criminal` | `binary (0/1)`| Target-helper flag highlighting if the case falls within a criminal court track. |

---

## 2. Reference Lookup Keys (The Translation Layers)

Because storing text variables millions of times across 81.2 million entries would cause extreme file bloating, the database isolates text names inside standalone lookup tables.

Your pipeline should import these files to interpret the raw code signals into clear categorical arrays or user-facing explanations:

* **`act_key.csv`**: Decodes `act` codes into literal text names (e.g., *Code of Civil Procedure, Negotiable Instruments Act*).
* **`section_key.csv`**: Decodes `section` codes into exact statutory definitions.
* **`type_name_key.csv`**: Decodes `type_name` identifiers into human-readable definitions (e.g., *Commercial Suit, Money Recovery Suit, Summary Suit*). **Mandatory step for filtering commercial scopes.**
* **`disp_name_key.csv`**: Translates final outcomes (e.g., *Dismissed, Settled, Allowed, Withdrawn*). **Mandatory step for training the Litigate vs. Settle logic**.
* **`purpose_name_key.csv`**: Translates the structural purpose behind active hearings (e.g., *For Evidence, For Arguments, For Admission*).
* **`cases_state_key.csv`**: Translates `state_code` into regional strings (e.g., *Maharashtra, Delhi, Karnataka*).
* **`cases_district_key.csv`**: Translates `dist_code` into localized district geographic names.
* **`cases_court_key.csv`**: Translates `court_no` into descriptive courtroom infrastructure groupings.

In [10]:
type_key = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\keys\\type_name_key.csv")

In [11]:
type_key.head()

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [12]:
type_key['type_clean'] = type_key['type_name_s'].astype(str).str.lower().str.strip()

In [13]:
commercial_pattern = 'commercial|money|recovery|contract|summary|cheque|negotiable|t\.s\.|scc|\(sc\)'

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\Karnaveer Singh\AppData\Local\Temp\ipykernel_3276\1033891159.py:1: SyntaxWarning: invalid escape sequence '\.'
  commercial_pattern = 'commercial|money|recovery|contract|summary|cheque|negotiable|t\.s\.|scc|\(sc\)'

In [14]:
commercial_rows = type_key[type_key['type_clean'].str.contains(commercial_pattern, na=False)]

commercial_rows

,year,type_name,type_name_s,count,type_clean
0,2010,1.0,(m) t.s.,18,(m) t.s.
1,2010,2.0,(sc),2,(sc)
49,2010,50.0,138 negotiable instrument act,2,138 negotiable instrument act
122,2010,123.0,2.money suit,151,2.money suit
150,2010,151.0,4.money execution,18,4.money execution
...,...,...,...,...,...
62319,2018,7139.0,t.s.(r.c.r),1,t.s.(r.c.r)
62376,2018,7196.0,title money suit,2,title money suit
62410,2018,7230.0,title suit(commercial),1,title suit(commercial)
62668,2018,7488.0,xxxx--scc suit,9,xxxx--scc suit
62676,2018,7496.0,xxxxexscc,1,xxxxexscc

In [15]:
target_commercial_codes = set(commercial_rows['type_name'].unique())

In [16]:
strict_whitelist = [
    'os', 'o.s.', 'xxxx--o s',
    'money suit h a', 'money suit  t',
    'original suit/hm',
    'original (title/partition/money) suit',
    'suit for mandatory injunction(civil)',
    'suit for cancellation of agreement',
    'suit for recovery',
    'summary suit', 'sum',
    'stc',  # summons to case — civil
    'miscellaneous civil',
    'money suit',
]

# Get the type_name codes for these
strict_codes = type_key[
    type_key['type_name_s'].str.strip().str.lower().isin([x.lower() for x in strict_whitelist])
]['type_name'].unique()

print(f"Strict codes: {len(strict_codes)}")

Strict codes: 116

In [17]:
import pandas as pd

# 1. Your combined list of commercial and cheque bounce numeric codes
# (Extracted from your type_name_key filtering steps)
commercial_codes_set = set(strict_codes)  # Start with the strict whitelist codes

case_files = [
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2010.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2011.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2012.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2013.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2014.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2015.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2016.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2017.csv",
    r"C:\Users\Karnaveer Singh\Justice_Hq\csv\cases\cases_2018.csv",
]

filtered_slices = []

print("--- Starting Dynamic Commercial Extraction Pipeline ---")
for path in case_files:
    # Extract year string from path for clean logging
    year_label = path.split("_")[-1].replace(".csv", "")
    print(f"Streaming and filtering cases for Year: {year_label}...")
    
    # Read the file one year at a time to protect laptop RAM
    year_df = pd.read_csv(path)
    
    # Single, bulletproof filter: Grab only the target commercial rows
    commercial_slice = year_df[year_df['type_name'].isin(commercial_codes_set)].copy()
    
    # Save the compressed slice and immediately wipe the heavy raw dataframe from memory
    filtered_slices.append(commercial_slice)
    del year_df

# Concatenate only the clean commercial files together
comm_cases = pd.concat(filtered_slices, ignore_index=True)

print(f"\n[SUCCESS] Pipeline Complete!")
print(f"Total isolated commercial rows ready for ML modeling: {len(comm_cases):,}")

--- Starting Dynamic Commercial Extraction Pipeline ---
Streaming and filtering cases for Year: 2010...
Streaming and filtering cases for Year: 2011...
Streaming and filtering cases for Year: 2012...
Streaming and filtering cases for Year: 2013...
Streaming and filtering cases for Year: 2014...
Streaming and filtering cases for Year: 2015...
Streaming and filtering cases for Year: 2016...
Streaming and filtering cases for Year: 2017...
Streaming and filtering cases for Year: 2018...

[SUCCESS] Pipeline Complete!
Total isolated commercial rows ready for ML modeling: 5,739,259

In [18]:
comm_cases.head()

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list
0,01-03-02-207401000012010,2010,1,3,2,MHJG040004222010,district and sessions court,1 female,0 male,0,-9998,4784.0,4511.0,25,2010-02-11,2011-03-30,2010-02-26,2011-03-16,2011-03-30
1,01-03-02-207401000012011,2010,1,3,2,MHJG040039232010,district and sessions court,0 male,1 female,-9999,0,4784.0,4882.0,25,2010-12-24,2012-07-11,2011-01-10,2012-07-09,2012-07-11
2,01-03-02-207401000022010,2010,1,3,2,MHJG040006132010,district and sessions court,1 female,0 male,-9999,0,4784.0,4293.0,43,2010-03-02,2012-06-25,2010-03-08,2012-06-18,2012-06-25
3,01-03-02-207401000022011,2010,1,3,2,MHJG040036672010,district and sessions court,1 female,0 male,-9999,0,4784.0,3006.0,25,2010-12-04,2012-12-17,2011-02-21,2012-11-30,2012-12-17
4,01-03-02-207401000032010,2010,1,3,2,MHJG040016072010,district and sessions court,-9998 unclear,1 female,-9999,0,4784.0,3734.0,30,2010-06-10,2011-01-03,2010-06-14,2010-12-20,2011-01-03

In [19]:
df = comm_cases.merge(act_key, on='ddl_case_id', how='left')
df.head()

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,...,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list,act,section,bailable_ipc,number_sections_ipc,criminal
0,01-03-02-207401000012010,2010,1,3,2,MHJG040004222010,district and sessions court,1 female,0 male,0,...,2010-02-11,2011-03-30,2010-02-26,2011-03-16,2011-03-30,7276.0,1345422.0,NaN,NaN,0.0
1,01-03-02-207401000012011,2010,1,3,2,MHJG040039232010,district and sessions court,0 male,1 female,-9999,...,2010-12-24,2012-07-11,2011-01-10,2012-07-09,2012-07-11,16320.0,635313.0,NaN,NaN,0.0
2,01-03-02-207401000022010,2010,1,3,2,MHJG040006132010,district and sessions court,1 female,0 male,-9999,...,2010-03-02,2012-06-25,2010-03-08,2012-06-18,2012-06-25,16320.0,635313.0,NaN,NaN,0.0
3,01-03-02-207401000022011,2010,1,3,2,MHJG040036672010,district and sessions court,1 female,0 male,-9999,...,2010-12-04,2012-12-17,2011-02-21,2012-11-30,2012-12-17,16320.0,643810.0,NaN,NaN,0.0
4,01-03-02-207401000032010,2010,1,3,2,MHJG040016072010,district and sessions court,-9998 unclear,1 female,-9999,...,2010-06-10,2011-01-03,2010-06-14,2010-12-20,2011-01-03,16320.0,678419.0,NaN,NaN,0.0

In [20]:
df = df[df['criminal'] == 0].copy()
print(f"Rows after criminal filter: {len(df):,}")
print(df['criminal'].value_counts())

Rows after criminal filter: 4,157,671
criminal
0.0    4157671
Name: count, dtype: int64

In [21]:
df['year'].value_counts().sort_index()

year
2010    119430
2011    154390
2012    220677
2013    268531
2014    460321
2015    562031
2016    657119
2017    782294
2018    932878
Name: count, dtype: int64

In [22]:
print('all_cases shape:', df.shape)
print(df['year'].value_counts().sort_index())
print('comm_cases shape:', df.shape)
print(df['year'].value_counts().sort_index())

all_cases shape: (4157671, 24)
year
2010    119430
2011    154390
2012    220677
2013    268531
2014    460321
2015    562031
2016    657119
2017    782294
2018    932878
Name: count, dtype: int64
comm_cases shape: (4157671, 24)
year
2010    119430
2011    154390
2012    220677
2013    268531
2014    460321
2015    562031
2016    657119
2017    782294
2018    932878
Name: count, dtype: int64

In [23]:
df.columns

Index(['ddl_case_id', 'year', 'state_code', 'dist_code', 'court_no', 'cino',
       'judge_position', 'female_defendant', 'female_petitioner',
       'female_adv_def', 'female_adv_pet', 'type_name', 'purpose_name',
       'disp_name', 'date_of_filing', 'date_of_decision', 'date_first_list',
       'date_last_list', 'date_next_list', 'act', 'section', 'bailable_ipc',
       'number_sections_ipc', 'criminal'],
      dtype='str')

In [24]:
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
print(f"\nMissing values:\n{df.isnull().sum()}")

Rows: 4,157,671
Columns: 24

Missing values:
ddl_case_id                  0
year                         0
state_code                   0
dist_code                    0
court_no                     0
cino                         0
judge_position               0
female_defendant             0
female_petitioner            0
female_adv_def               0
female_adv_pet               0
type_name                    0
purpose_name            171468
disp_name                    0
date_of_filing               0
date_of_decision       1122513
date_first_list         177620
date_last_list            2880
date_next_list          111764
act                       2022
section                      0
bailable_ipc           4157671
number_sections_ipc    4157671
criminal                     0
dtype: int64

In [25]:
# Convert dates
df['date_of_filing'] = pd.to_datetime(df['date_of_filing'], errors='coerce')
df['date_of_decision'] = pd.to_datetime(df['date_of_decision'], errors='coerce')

# Calculate resolution time in days
resolved = df[df['date_of_decision'].notna()].copy()
resolved['resolution_days'] = (resolved['date_of_decision'] - resolved['date_of_filing']).dt.days

# Drop negative or zero values (data errors)
resolved = resolved[resolved['resolution_days'] > 0]

print(f"Resolved cases: {len(resolved):,}")
print(f"\nResolution time (days):")
print(resolved['resolution_days'].describe())
print(f"\nMedian resolution: {resolved['resolution_days'].median():.0f} days ({resolved['resolution_days'].median()/365:.1f} years)")

Resolved cases: 2,203,540

Resolution time (days):
count    2.203540e+06
mean     5.425524e+02
std      6.094108e+03
min      1.000000e+00
25%      7.700000e+01
50%      2.930000e+02
75%      7.310000e+02
max      1.109385e+06
Name: resolution_days, dtype: float64

Median resolution: 293 days (0.8 years)

In [26]:
# Diagnose the tail


# this is error in data entry found out by diagnosis
print("Distribution of extreme values:")
print(f"Cases over 10 years (3650 days): {(resolved['resolution_days'] > 3650).sum():,}")
print(f"Cases over 20 years (7300 days): {(resolved['resolution_days'] > 7300).sum():,}")
print(f"Cases over 50 years (18250 days): {(resolved['resolution_days'] > 18250).sum():,}")

# What are the filing dates of these extreme cases?
extreme = resolved[resolved['resolution_days'] > 18250]
print(f"\nExtreme cases filing dates:")
print(extreme['date_of_filing'].dt.year.value_counts())
print(f"\nExtreme cases decision dates:")
print(extreme['date_of_decision'].dt.year.value_counts())

Distribution of extreme values:
Cases over 10 years (3650 days): 91
Cases over 20 years (7300 days): 75
Cases over 50 years (18250 days): 74

Extreme cases filing dates:
date_of_filing
2012    17
2013    14
2014    12
2010    11
2011    11
2015     5
2016     3
2017     1
Name: count, dtype: int64

Extreme cases decision dates:
date_of_decision
5000    64
5001     2
2091     1
2078     1
3012     1
5013     1
2501     1
2105     1
2079     1
5055     1
Name: count, dtype: int64

In [27]:
# Cap at 30 years - anything beyond is a data entry error
resolved_clean = resolved[resolved['resolution_days'] <= 10950].copy()

print(f"Dropped: {len(resolved) - len(resolved_clean):,} corrupt cases")
print(f"Clean resolved cases: {len(resolved_clean):,}")
print(f"\nFinal resolution time:")
print(f"Median: {resolved_clean['resolution_days'].median():.0f} days ({resolved_clean['resolution_days'].median()/365:.1f} years)")
print(f"Mean: {resolved_clean['resolution_days'].mean():.0f} days")
print(f"90th percentile: {resolved_clean['resolution_days'].quantile(.90):.0f} days ({resolved_clean['resolution_days'].quantile(.90)/365:.1f} years)")

# Target variable
def resolution_bucket(days):
    if days <= 180:
        return '0_under_6months'
    elif days <= 730:
        return '1_six_to_24months'
    else:
        return '2_over_2years'

resolved_clean['resolution_bucket'] = resolved_clean['resolution_days'].apply(resolution_bucket)

print("\nTarget variable distribution:")
dist = resolved_clean['resolution_bucket'].value_counts().sort_index()
pct = resolved_clean['resolution_bucket'].value_counts(normalize=True).mul(100).round(1).sort_index()
for bucket, count, p in zip(dist.index, dist.values, pct.values):
    print(f"  {bucket}: {count:,} cases ({p}%)")

Dropped: 75 corrupt cases
Clean resolved cases: 2,203,465

Final resolution time:
Median: 293 days (0.8 years)
Mean: 509 days
90th percentile: 1347 days (3.7 years)

Target variable distribution:
  0_under_6months: 852,085 cases (38.7%)
  1_six_to_24months: 800,170 cases (36.3%)
  2_over_2years: 551,210 cases (25.0%)

In [28]:
print(resolved_clean['type_name'].value_counts().head(20))

type_name
5103.0    185845
4877.0    162819
5031.0    139326
5098.0    122481
4848.0    115141
4650.0    108882
3692.0    103035
4274.0     93305
4783.0     74425
5006.0     71700
4826.0     65669
5070.0     62645
6748.0     61802
4766.0     61160
4932.0     56549
6769.0     52875
5003.0     47663
4575.0     42611
4974.0     36388
6652.0     36266
Name: count, dtype: int64

In [29]:
state_df = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\keys\\cases_state_key.csv")
type_df = pd.read_csv("C:\\Users\\Karnaveer Singh\\Justice_Hq\\csv\\keys\\type_name_key.csv")

# state_df.head()
type_df.head()

   year  type_name         type_name_s  count
0  2010        1.0            (m) t.s.     18
1  2010        2.0                (sc)      2
2  2010        3.0          ..mact 166     97
3  2010        4.0  04 complaint cases     19
4  2010        5.0    04 criminal case     21

In [30]:
# Deduplicate state_key first
state_key_dedup = state_df[['state_code', 'state_name']].drop_duplicates(subset='state_code')

# Redo the merge
state_stats = resolved_clean.groupby('state_code')['resolution_days'].agg([
    'median', 'count'
]).round(0).reset_index()
state_stats.columns = ['state_code', 'median_days', 'case_count']
state_stats = state_stats[state_stats['case_count'] > 1000]
state_stats = state_stats.merge(state_key_dedup, on='state_code', how='left')

print("5 Fastest states:")
print(state_stats.sort_values('median_days').head()[['state_name', 'median_days', 'case_count']])

print("\n5 Slowest states:")
print(state_stats.sort_values('median_days').tail()[['state_name', 'median_days', 'case_count']])

5 Fastest states:
        state_name  median_days  case_count
20          Sikkim         29.0        1112
19  Madhya Pradesh         40.0      154312
12   Uttar Pradesh         53.0      145090
23      Chandigarh         55.0        1423
22           Delhi         63.0        4734

5 Slowest states:
   state_name  median_days  case_count
3      Kerala        475.0      333718
24  Telangana        524.0      130046
8   Rajasthan        696.0        5309
7       Bihar        747.0        4244
10     Orissa       1074.0        3772

In [31]:
print(type_key.columns.tolist())
print(type_key.head())

['year', 'type_name', 'type_name_s', 'count', 'type_clean']
   year  type_name         type_name_s  count          type_clean
0  2010        1.0            (m) t.s.     18            (m) t.s.
1  2010        2.0                (sc)      2                (sc)
2  2010        3.0          ..mact 166     97          ..mact 166
3  2010        4.0  04 complaint cases     19  04 complaint cases
4  2010        5.0    04 criminal case     21    04 criminal case

In [32]:
# Deduplicate type key - keep just code and readable name
type_key_dedup = type_key[['type_name', 'type_name_s']].drop_duplicates(subset='type_name')

# Get top case types
type_counts = resolved_clean['type_name'].value_counts().reset_index()
type_counts.columns = ['type_name', 'count']

# Merge
type_counts = type_counts.merge(type_key_dedup, on='type_name', how='left')

print(type_counts.head(20)[['type_name_s', 'count']])

                             type_name_s   count
0                            summon case  185845
1                            ss cases(s)  162819
2                 suit for permenant inj  139326
3                          summary trail  122481
4                              spl.kptcl  115141
5               special case (sc/st act)  108882
6                                     os  103035
7                    restoration app.ulp   93305
8                 spl. marriage petition   74425
9       suit for mandtoryand  perptl inj   71700
10                               spl.c.c   65669
11                     suit fr dissolutn   62645
12         withdrawal of suits 0-23 , r1   61802
13                     spl. case e.c act   61160
14                       succession case   56549
15                             xxxx--o s   52875
16  suit for mandatory injunction(civil)   47663
17                    sessions case(svr)   42611
18         suit for decl. and mand. inj.   36388
19                                   uba   36266

In [33]:
all_types = df.merge(type_key[['type_name','type_name_s']].drop_duplicates(), 
                     on='type_name', how='left')['type_name_s'].value_counts()

print(all_types.head(50))

type_name_s
os                                       1685039
sum                                       766443
o.s.                                      735812
stc                                       453469
suit fr dissolutn                         439273
mwapp lc                                  349891
t.i.                                      340398
p  and  sc                                263705
summon case                               263131
sc criminal                               263131
rcs a                                     263131
police case pw                            263131
petition us 127 of cr.pc                  263131
p.a. apeal                                263131
os execution                              263131
rcr.                                      255562
original suit/hm                          253919
summary trail                             248085
sc /st act                                248085
police  challan                           248085
petition u/s 156(3) cr.p.c.               248085
p. p. appeal                              248085
other misc.cri.appln                      248085
partion suit                              238674
s.r                                       236580
raj exe act                               236580
petition under order 9 rule 13            236580
petition  f                               236580
orig.suit                                 236580
p & s act                                 236580
original  suit                            236580
r.appeal                                  235892
suit for permenant inj                    235429
s.c.                                      235429
peta act                                  235429
pc                                        235429
offence 366,376 rpc                       235429
oma                                       235429
op sma                                    235429
original (title/partition/money) suit     228854
partion suit / title partion suit         218816
pfa                                       218738
spl.kptcl                                 215381
others                                    214740
n.i. act                                  214740
ss cases(s)                               212179
rent miscellaneous                        212179
ngr                                       212179
mv. act                                   212179
wca nf                                    202693
Name: count, dtype: int64

In [48]:
resolved_clean.shape

(2203465, 26)

In [50]:
resolved_clean.to_csv(r'C:\Users\Karnaveer Singh\Justice_Hq\data\commercial_clean.csv', index=False)

In [51]:
resolved_clean

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,...,date_first_list,date_last_list,date_next_list,act,section,bailable_ipc,number_sections_ipc,criminal,resolution_days,resolution_bucket
0,01-03-02-207401000012010,2010,1,3,2,MHJG040004222010,district and sessions court,1 female,0 male,0,...,2010-02-26,2011-03-16,2011-03-30,7276.0,1345422.0,NaN,NaN,0.0,412,1_six_to_24months
1,01-03-02-207401000012011,2010,1,3,2,MHJG040039232010,district and sessions court,0 male,1 female,-9999,...,2011-01-10,2012-07-09,2012-07-11,16320.0,635313.0,NaN,NaN,0.0,565,1_six_to_24months
2,01-03-02-207401000022010,2010,1,3,2,MHJG040006132010,district and sessions court,1 female,0 male,-9999,...,2010-03-08,2012-06-18,2012-06-25,16320.0,635313.0,NaN,NaN,0.0,846,2_over_2years
3,01-03-02-207401000022011,2010,1,3,2,MHJG040036672010,district and sessions court,1 female,0 male,-9999,...,2011-02-21,2012-11-30,2012-12-17,16320.0,643810.0,NaN,NaN,0.0,744,2_over_2years
4,01-03-02-207401000032010,2010,1,3,2,MHJG040016072010,district and sessions court,-9998 unclear,1 female,-9999,...,2010-06-14,2010-12-20,2011-01-03,16320.0,678419.0,NaN,NaN,0.0,207,1_six_to_24months
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5739254,32-01-01-204800000032018,2018,32,1,1,UTDN010001382018,principal district and sessions court,0 male,-9998 unclear,-9999,...,2018-01-31,2018-09-08,2018-09-08,4069.0,1441460.0,NaN,NaN,0.0,221,1_six_to_24months
5739255,32-01-01-204800000042018,2018,32,1,1,UTDN010007542018,principal district and sessions court,0 male,-9998 unclear,-9999,...,2018-07-09,2018-08-07,2018-08-07,4069.0,1441460.0,NaN,NaN,0.0,32,0_under_6months
5739256,33-01-02-224200000012018,2018,33,1,2,LDKR020000142018,principal district judge,0 male,0 male,-9999,...,2018-04-06,2019-08-23,2019-08-23,4650.0,977848.0,NaN,NaN,0.0,521,1_six_to_24months
5739257,33-02-02-224500000012018,2018,33,2,2,LDLH020000682018,principal district judge,0 male,0 male,-9999,...,2018-10-06,2019-05-28,2019-05-28,4650.0,2022888.0,NaN,NaN,0.0,251,1_six_to_24months
5739258,33-02-02-224500000022018,2018,33,2,2,LDLH020001042018,principal district judge,0 male,0 male,0,...,2019-02-22,2019-12-23,2019-12-23,4650.0,2022888.0,NaN,NaN,0.0,359,1_six_to_24months